baseURL = 'https://websitesci.netlify.app/'
languageCode = 'id-id'
title = 'Website Sekolah Cinta Ilmu'
theme = "luique"

[build]
  noJSConfigInAssets = false  # Enable asset processing untuk SCSS

# ENABLE CSS minification untuk production
[minify]
  minifyOutput = true
  disableCSS = false   # Enable CSS minification
  disableHTML = false  # Enable HTML minification
  disableJS = false   # Bisa disable JS jika tidak butuh
  disableJSON = true
  disableSVG = true
  disableXML = true

[markup.goldmark.renderer]
  unsafe = true

[menu]

[[menu.main]]
  name = "Beranda"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Sejarah"
  url = "/services/"
  weight = 2

[[menu.main]]
  name = "Catatan Guru"
  url = "/blog/"
  weight = 3

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5

ignoreLogs = ['warning-goldmark-raw-html']

