baseURL = 'https://websitesci.netlify.app/'
languageCode = 'id-id'
title = 'Website Sekolah Cinta Ilmu'
theme = "luique"

[build]
  noJSConfigInAssets = false  # Enable asset processing untuk SCSS

# ENABLE CSS minification untuk production
[minify]
  minifyOutput = true
  disableCSS = false   # Enable CSS minification
  disableHTML = false  # Enable HTML minification
  disableJS = true     # Bisa disable JS jika tidak butuh
  disableJSON = true
  disableSVG = true
  disableXML = true

[markup.goldmark.renderer]
  unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']