baseURL = 'https://example.org/'
languageCode = 'id-id'
title = 'Website Sekolah Cinta Ilmu'
theme = "luique"

[build]
  noJSConfigInAssets = true
  writeStats = true

# DISABLE ALL MINIFICATION
[minify]
  minifyOutput = false
  disableCSS = true
  disableHTML = true
  disableJS = true
  disableJSON = true
  disableSVG = true
  disableXML = true
  disableTOML = true
  disableYAML = true

[caches]
  [caches.getjson]
    maxAge = -1
  [caches.getcsv]
    maxAge = -1
  [caches.images]
    maxAge = -1

[markup.goldmark.renderer]
  unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']